adding receiver mails via github secrets

diff --git a/.github/workflows/bot_daily_posting_pyzotero.yml b/.github/workflows/bot_daily_posting_pyzotero.yml
--- a/.github/workflows/bot_daily_posting_pyzotero.yml
+++ b/.github/workflows/bot_daily_posting_pyzotero.yml
@@ -27,6 +27,7 @@ jobs:
           if [ -z "${{ secrets.ZOTERO_LIBRARY_ID }}" ]; then echo "Missing ZOTERO_LIBRARY_ID"; exit 1; fi
           if [ -z "${{ secrets.SLACK_API_KEY }}" ]; then echo "Missing SLACK_API_KEY"; exit 1; fi
           if [ -z "${{ secrets.GMAIL_PASSWORD }}" ]; then echo "Missing GMAIL_PASSWORD"; exit 1; fi
+          if [ -z "${{ secrets.RECEIVER_MAILS }}" ]; then echo "Missing RECEIVER_MAILS"; exit 1; fi
         
       - name: Install dependencies
         run: |
@@ -55,7 +56,8 @@ jobs:
             --zotero_api_key "${{ secrets.ZOTERO_API_KEY }}" \
             --zotero_library_id "${{ secrets.ZOTERO_LIBRARY_ID }}" \
             --slack_token "${{ secrets.SLACK_API_KEY }}" \
-            --gmail_password "${{ secrets.GMAIL_PASSWORD }}"
+            --gmail_password "${{ secrets.GMAIL_PASSWORD }}" \
+            --receiver_mails "${{ secrets.RECEIVER_MAILS }}"
       
       - name: Upload state file to Google Drive
         run: |
