checking early in workflow if github secrets are set

diff --git a/.github/workflows/bot_daily_posting_pyzotero.yml b/.github/workflows/bot_daily_posting_pyzotero.yml
--- a/.github/workflows/bot_daily_posting_pyzotero.yml
+++ b/.github/workflows/bot_daily_posting_pyzotero.yml
@@ -19,6 +19,15 @@ jobs:
         with:
           python-version: '3.11'
 
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" ]; then echo "Missing GOOGLE_SERVICE_ACCOUNT_JSON"; exit 1; fi
+          if [ -z "${{ secrets.STATEFILE_FILE_ID }}" ]; then echo "Missing STATEFILE_FILE_ID"; exit 1; fi
+          if [ -z "${{ secrets.ZOTERO_API_KEY }}" ]; then echo "Missing ZOTERO_API_KEY"; exit 1; fi
+          if [ -z "${{ secrets.ZOTERO_LIBRARY_ID }}" ]; then echo "Missing ZOTERO_LIBRARY_ID"; exit 1; fi
+          if [ -z "${{ secrets.SLACK_API_KEY }}" ]; then echo "Missing SLACK_API_KEY"; exit 1; fi
+          if [ -z "${{ secrets.GMAIL_PASSWORD }}" ]; then echo "Missing GMAIL_PASSWORD"; exit 1; fi
+        
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
